<?php
return [
    'app/data/achievements.json' => [
        //Super Categories
        '"Feats of Strength"' => '"Великие подвиги"',
        '"Legacy"' => '"Наследие"',
        '"Character"' => '"Персонаж"',
        '"Quests"' => '"Задания"',
        '"Exploration"' => '"Исследования"',
        '"Dungeons & Raids"' => '"Подземелья и Рейды"',
        '"Professions"' => '"Профессии"',
        '"Reputation"' => '"Репутация"',
        '"World Events"' => '"Игровые события"',
        '"Pet Battles"' => '"Битвы питомцев"',
        '"Collections"' => '"Коллекции"',
        '"Expansion Features"' => '"Особый контент"',
        //Character
        '"Level"' => '"Уровень"',
        '"Gold"' => '"Золото"',
        '"Mounts"' => '"Маунты"',
        '"Items"' => '"Предметы"',
        '"Other"' => '"Другое"',
        //Quests
        '"Regular Counts"' => '"Задания"',
        '"Daily Counts"' => '"Ежедневные задания"',
        '"Dungeon Counts"' => '"Подземелья"',
        '"Themes"' => '"Тематические"',
        '"World"' => '"Локальные задания"',
        '"Other"' => '"Другое"',
        '"Zones"' => '"Локации"',
        '"Events"' => '"События"',
        '"Assaults"' => '"Нападения"',
        //Super Locations
        '"Battle for Azeroth"' => '"Битва за Азерот"',
        '"Legion"' => '"Легион"',
        '"Draenor"' => '"Дренор"',
        '"Pandaria"' => '"Пандария"',
        '"Cataclysm"' => '"Катаклизм"',
        '"Northrend"' => '"Нордсколл"',
        '"Outland"' => '"Запределье"',
        '"Kalimdor"' => '"Калимдор"',
        '"Eastern Kingdoms"' => '"Восточные Королевства"',
        // Locations
        '"Tiragarde Sound"' => '"Тирагардское Поморье"',
        '"Stormsong Valley"' => '"Долина Штормов"',
        '"Zuldazar"' => '"Зулдазар"',
        '"Vol\'dun"' => '"Вол\'Дун"',
        '"Nazmir"' => '"Назмир"',
        '"Highmountain"' => '"Крутогорье"',
        '"Stormheim"' => '"Штормхейм"',
        '"Suramar"' => '"Сурамар"',
        '"Broken Shore"' => '"Расколотый Берег"',
        '"Broken Shore: Buildings"' => '"Расколотый Берег: Постройки"',
        '"Argus"' => '"Аргус"',
    ],
];
